### PR TITLE
data: Updage Georgian to stage 5

### PR DESCRIPTION
**Pull request by behnam**
stage 5: Final revision of the text by Natia Bagbaia, addressing various
language issues in the OHCHR text. Reviewed by Natia Burduli.

Markup by Connie Bobroff and Behnam Esfahbod.

Closes GH-27.

### CODE REVIEW

**Comment by behnam** [comment]
@eric-muller, what do you think about this?

cc @conniebobroff.

**Comment by behnam** [comment]
@r12a, do you have any feedback here, as you were recently working on Georgian stuff? Know anyone who could confirm text-encoding quality here?

**Comment by r12a** [comment]
The differences seem to be all related to translation. My List characters app (https://r12a.github.io/app-listcharacters/)  tells me that both the current version and the proposed new version use the same Georgian character repertoire: the 32 letters ა ბ გ დ ე ვ ზ თ ი კ ლ მ ნ ო პ რ ს ტ უ ფ ქ ღ ყ შ ჩ ც ძ წ ჭ ხ ჯ ჰ are all mkhedruli, and none are deprecated or archaic afaik. There are no mtravruli, asomtravruli or nuskhuri characters in the text (as you'd expect). (See https://r12a.github.io/pickers/geor-ka/?text=%E1%83%90%E1%83%91%E1%83%92%E1%83%93%E1%83%94%E1%83%95%E1%83%96%E1%83%97%E1%83%98%E1%83%99%E1%83%9A%E1%83%9B%E1%83%9C%E1%83%9D%E1%83%9E%E1%83%A0%E1%83%A1%E1%83%A2%E1%83%A3%E1%83%A4%E1%83%A5%E1%83%A6%E1%83%A7%E1%83%A8%E1%83%A9%E1%83%AA%E1%83%AB%E1%83%AC%E1%83%AD%E1%83%AE%E1%83%AF%E1%83%B0 and click on Analyse text.)  There are no tricky normalisation or alternative code point issues for Georgian afaik.

Is that the kind of thing you were looking for?  (I can't judge the translation.)

**Comment by behnam** [comment]
This is great, @r12a. Appreciate looking into it the encoding.

Considering the technical encoding quality, and the translation being reviewed by a few natives already, I think we have enough confidence to merge it in. 🎉

**Pull request merged**
