### PR TITLE
Add Zarma [dje]

### PR DESCRIPTION
**Pull request by moyogo**
https://www.ohchr.org/en/human-rights/universal-declaration/translations/zarma was added on 10.05.2023.

### CODE REVIEW

**Comment by eric-muller** [comment]
In udhr_dje.xml, the xml:lang attribute should probably be dje, not fr.

**Comment by eric-muller** [comment]
Also, the current practice is to name the translations udhr_<number>, rather than udhr_<langtag>. 043 is the next available. As we are getting in less common languages, their identification is less reliable, and we sometime want to change it; and since we don't want to rename the translations (for stability), it becomes cumbersome to have a mismatch.

**Comment by moyogo** [comment]
@eric-muller OK, I wasn’t sure about the number.

I fixed the 'fr' to 'dje'
I renamed the files to udhr_043 and status_043 and updated the index. I guess Github swallowed the &lt;.*&gt; in your reply but it seems clear.

Is the status_043 correct?

**Comment by eric-muller** [comment]
Thanks!  I did a couple more fixes. Sorry that the process is a bit involved.

Eric.

**Comment by moyogo** [comment]
Thank you. Sorry I missed a couple of the "dje" in the fix and the direction.

**Pull request merged**
