### PR TITLE
[tha2] Fix incorrect punctuation spacing for (ๆ)

### PR DESCRIPTION
**Pull request by kagiura**
The Thai symbol ๆ, used for repeating words, requires a space both in front and behind it. The current Thai (2) version has a small mistake of not having a space in front of it (preamble, paragraph 4)

> โดยที่เป็นการจำเป็นที่จะส่งเสริมพัฒนาการแห่งความสัมพันธ์ฉันมิตรระหว่างชาติต่างๆ

Corrected: 

> โดยที่เป็นการจำเป็นที่จะส่งเสริมพัฒนาการแห่งความสัมพันธ์ฉันมิตรระหว่างชาติต่าง ๆ

Source: https://www.unicode.org/udhr/d/udhr_tha2.html, originally spotted on googlefonts/noto-fonts#2353

Edit: I already signed the CLA if anything, lets hope it updates soon 🤔 .

### CODE REVIEW

**Comment by yuuukun** [comment]
(For the record, the link @CLAassistant doesn't work..? Tried different browsers/incognito with no success.
image

**Comment by eric-muller** [comment]
Some space makes sense, but shouldn't it be some kind of non-breaking space, such as U+00A0 NO-BREAK SPACE or U+202F NARROW NO-BREAK SPACE?

**Comment by r12a** [comment]
See also https://github.com/w3c/sealreq/issues/45#issuecomment-976863229, which argues for use of NNBSP, rather than U+00A0.

**Comment by yuuukun** [comment]
Ah, right, my mistake. I do agree on using a NBSP more than an NNBSP, considering the Thai Royal style guide does have 2 types of a space (large and small), and the space required in front of and behind a Mai Yamok is a small space (equivalent to a normal-width space for latin characters) already, so using an NNBSP would make it even smaller and potentially incorrect. 

(I don't have the book to cite the sources so I'm just going off memory, but I'm pretty confident that the space in front of and behind should be the same width.)

**Comment by r12a** [comment]
@kamishirorui as mentioned in https://github.com/w3c/sealreq/issues/45#issuecomment-976863229, the thing to note about using NBSP before ๆ is that it expands during justification, whereas  NNBSP does not.

There is also some discussion of Thai spaces in https://github.com/w3c/sealreq/issues/46, which describes the difference between small spaces and wide spaces. There are a number of potential ways of achieving that, one of which may be to use an EM SPACE for the wide (inter-sentence) space. (There is not yet a clear proposal for which way to go.)

**Comment by eric-muller** [comment]
No action for a year, closing this pull request.

**Pull request closed without merging**
